export type EventRecord = {
    Event_ID: number;
    Event_Title: string;
    Event_Type_ID: number;
    Congregation_ID: number;
    Location_ID: null | number;
    Meeting_Instructions: null | string;
    Description: null | string;
    Program_ID: number;
    Primary_Contact: number;
    Participants_Expected: null | number;
    Minutes_for_Setup: number;
    Event_Start_Date: string;
    Event_End_Date: string;
    Minutes_for_Cleanup: number;
    Cancelled: boolean;
    _Approved: boolean;
    Public_Website_Settings: null | string;
    Visibility_Level_ID: number;
    Featured_On_Calendar: boolean;
    Online_Registration_Product: null | string;
    Registration_Form: null | string;
    Registration_Start: string;
    Registration_End: string;
    Registration_Active: boolean;
    Register_Into_Series: boolean;
    External_Registration_URL: null | string;
    _Web_Approved: boolean;
    Force_Login: boolean;
    Check_in_Information: null | string;
    Allow_Check_in: boolean;
    Ignore_Program_Groups: boolean;
    Prohibit_Guests: boolean;
    Search_Results: number;
    Early_Check_in_Period: null | string;
    Late_Check_in_Period: null | string;
    Notification_Settings: null | string;
    Registrant_Message: null | string;
    Days_Out_to_Remind: null | number;
    Optional_Reminder_Message: null | string;
    Attendee_Message: null | string;
    Send_To_Heads: boolean;
    Other_Event_Information: null | string;
    Parent_Event_ID: null | number;
    Priority_ID: null | number;
    On_Connection_Card: boolean;
    Accounting_Information: null | string;
    On_Donation_Batch_Tool: boolean;
    Project_Code: null | string;
    Online_Meeting_Link: null | string;
    Read_More_URL: null | string;
    Allow_Self_Checkin: boolean;
    Minor_Registration: boolean;
    Allow_Email: boolean;
    Show_Building_Room_Info: boolean;
    Convert_Default_Contacts: boolean;
}

export type Event = {
    eventID: number;
    eventTitle: string;
    eventTypeID: number;
    congregationID: number;
    locationID: null | number;
    meetingInstructions: null | string;
    description: null | string;
    programID: number;
    primaryContact: number;
    participantsExpected: null | number;
    minutesForSetup: number;
    eventStartDate: string;
    eventEndDate: string;
    minutesForCleanup: number;
    cancelled: boolean;
    approved: boolean;
    publicWebsiteSettings: null | string;
    visibilityLevelID: number;
    featuredOnCalendar: boolean;
    onlineRegistrationProduct: null | string;
    registrationForm: null | string;
    registrationStart: string;
    registrationEnd: string;
    registrationActive: boolean;
    registerIntoSeries: boolean;
    externalRegistrationURL: null | string;
    webApproved: boolean;
    forceLogin: boolean;
    checkInInformation: null | string;
    allowCheckin: boolean;
    ignoreProgramGroups: boolean;
    prohibitGuests: boolean;
    searchResults: number;
    earlyCheckinPeriod: null | string;
    lateCheckinPeriod: null | string;
    notificationSettings: null | string;
    registrantMessage: null | string;
    daysOutToRemind: null | number;
    optionalReminderMessage: null | string;
    attendeeMessage: null | string;
    sendToHeads: boolean;
    otherEventInformation: null | string;
    parentEventID: null | number;
    priorityID: null | number;
    onConnectionCard: boolean;
    accountingInformation: null | string;
    onDonationBatchTool: boolean;
    projectCode: null | string;
    onlineMeetingLink: null | string;
    readMoreURL: null | string;
    allowSelfCheckin: boolean;
    minorRegistration: boolean;
    allowEmail: boolean;
    showBuildingRoomInfo: boolean;
    convertDefaultContacts: boolean;
}

